# Lab 3.3 - Notebook Siswa

## Gambaran Umum

Lab ini tidak melanjutkan skenario penyedia pemeliharaan kesehatan. Sebaliknya, Anda akan bekerja dengan data dari [set data automobile] (https://archive.ics.uci.edu/ml/datasets/Automobile).

Di lab ini, Anda akan:

- Mengkodekan data kategoris ordinal
- Mengkodekan data kategoris non-ordinal

## Tentang set data ini

Set data ini terdiri dari tiga jenis entitas: 

1. Spesifikasi sebuah mobil dalam hal berbagai karakteristik
2. Peringkat risiko asuransinya yang ditetapkan
3. Kerugiannya dinormalisasi dalam penggunaan dibandingkan dengan mobil lain

Peringkat kedua sesuai dengan sejauh mana mobil lebih berisiko daripada harga yang ditunjukkan. Mobil pada awalnya diberi simbol faktor risiko yang terkait dengan harganya. Kemudian, jika lebih berisiko (atau kurang berisiko), simbol ini disesuaikan dengan memindahkannya ke atas (atau ke bawah) skala. Aktuaria menyebut proses ini *simbol*. Nilai *+3* menunjukkan bahwa mobil berisiko. Nilai *-3* menunjukkan bahwa mobil mungkin aman.

Faktor ketiga adalah pembayaran kerugian rata-rata relatif per tahun kendaraan yang diasuransikan. Nilai ini dinormalisasi untuk semua mobil dalam klasifikasi ukuran tertentu (dua pintu kecil, station wagon, gaya sports atau spesialisasi, dan lain-lain). Ini merupakan kerugian rata-rata per mobil per tahun.

**Catatan:** Beberapa atribut dalam basis data dapat digunakan sebagai atribut *kelas*.

## Informasi atribut

Atribut: Rentang Atribut

1. lambang: -3, -2, -1, 0, 1, 2, 3.
1. kerugian yang dinormalisasi: kontinu dari 65 hingga 256.
1. jenis bahan bakar: diesel, gas.
1. aspiration: std, turbo.
1. jumlah pintu: empat, dua.
1. jenis bodi: hardtop, wagon, sedan, hatchback, dapat diubah.
1. roda penggerak: 4wd, fwd, rwd.
1. lokasi mesin: depan, belakang.
1. dasar roda: Kontinu dari 86,6 120,9.
1. panjang: kontinu dari 141,1 hingga 208,1.
1. lebar: kontinu dari 60,3 hingga 72,3.
1. tinggi: kontinu dari 47,8 sampai 59,8.
1. berat trotoar: kontinu dari 1488 hingga 4066.
1. jenis mesin: dohc, dohcv, l, ohc, ohcf, ohcv, rotor.
1. jumlah silinder: delapan, lima, empat, enam, tiga, dua belas, dua.
1. ukuran mesin: kontinu dari 61 sampai 326.
1. sistem bahan bakar: 1bbl, 2bbl, 4bbl, idi, mfi, mpfi, spdi, spfi.
1. lubang: kontinu dari 2,54 hingga 3,94.
1. stroke: kontinu dari 2.07 ke 4.17.
1. rasio kompresi: kontinu dari 7 sampai 23.
1. tenaga kuda: kontinu dari 48 hingga 288.
1. puncak rpm: kontinu dari 4150 hingga 6600.
1. kota-mpg: kontinu dari 13 hingga 49.
1. jalan raya mpg: kontinu dari 16 hingga 54.
1. harga: kontinu dari 5118 untuk 45400.

## Atribusi Set Data

Set data ini diperoleh dari:
Dua, D. dan Graff, C. (2019). Tempat Penyimpanan Machine Learning UCI (http://archive.ics.uci.edu/ml). Irvine, CA: University of California, Sekolah Informasi dan Ilmu Komputer.

# Langkah 1: Mengimpor dan melihat isi data

Anda akan mulai dengan memeriksa data dalam set data.

Untuk mendapatkan hasil maksimal dari lab ini, baca instruksi dan kode sebelum Anda menjalankan sel. Luangkan waktu untuk bereksperimen!

Mulailah dengan mengimpor paket pandas dan menetapkan beberapa pilihan tampilan default.

In [1]:
import pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

Selanjutnya, masukkan muatan set data ke dalam pandas DataFrame.

Data tidak berisi header, sehingga Anda akan menentukan nama-nama kolom dalam variabel yang bernama `col_names` untuk atribut yang tercantum dalam deskripsi set data.

In [3]:
url = "imports-85.csv"

col_names = ['symboling','normalized-losses','fuel-type','aspiration',
             'num-of-doors','body-style','drive-wheels','engine-location',
             'wheel-base','length','width','height','curb-weight',
             'engine-type','num-of-cylinders','engine-size','fuel-system',
             'bore','stroke','compression-ratio','horsepower','peak-rpm',
             'city-mpg','highway-mpg','price']

df_car = pd.read_csv(
    url,
    sep=',',
    names=col_names,
    na_values="?",
    header=None
)

Pertama, untuk melihat jumlah baris (contoh) dan kolom (fitur), Anda akan menggunakan `shape`.

In [4]:
df_car.shape

(205, 25)

Selanjutnya, periksa data dengan menggunakan metode `head`.

In [5]:
df_car.head(5)

   symboling  normalized-losses fuel-type aspiration num-of-doors   body-style drive-wheels engine-location  wheel-base  length  width  height  curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price
0          3                NaN       gas        std          two  convertible          rwd           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  13495.0
1          3                NaN       gas        std          two  convertible          rwd           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  16500.0
2          1                NaN       gas        std          two    hatchback          rwd           front        94.5   171.2   65.5    52.4         2823        ohcv              six          152        mpfi  2.68    3.47                9.0       154.0    5000.0        19           26  16500.0
3          2              164.0       gas        std         four        sedan          fwd           front        99.8   176.6   66.2    54.3         2337         ohc             four          109        mpfi  3.19    3.40               10.0       102.0    5500.0        24           30  13950.0
4          2              164.0       gas        std         four        sedan          4wd           front        99.4   176.6   66.4    54.3         2824         ohc             five          136        mpfi  3.19    3.40                8.0       115.0    5500.0        18           22  17450.0

Ada 25 kolom. Beberapa kolom memiliki nilai numerik, namun banyak di antaranya mengandung teks.

Untuk menampilkan informasi tentang kolom, gunakan metode `info` ini.

In [6]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    float64
 2   fuel-type          205 non-null    object
 3   aspiration         205 non-null    object
 4   num-of-doors       203 non-null    object
 5   body-style         205 non-null    object
 6   drive-wheels       205 non-null    object
 7   engine-location    205 non-null    object
 8   wheel-base         205 non-null    float64
 9   length             205 non-null    float64
 10  width              205 non-null    float64
 11  height             205 non-null    float64
 12  curb-weight        205 non-null    int64
 13  engine-type        205 non-null    object
 14  num-of-cylinders   205 non-null    object
 15  engine-size        205 non-null    int64
 16  fuel-system        205 non-null    object
 17  bore               201 non-null    float64
 18  stroke             201 non-null    float64
 19  compression-ratio  205 non-null    float64
 20  horsepower         203 non-null    float64
 21  peak-rpm           203 non-null    float64
 22  city-mpg           205 non-null    int64
 23  highway-mpg        205 non-null    int64
 24  price              201 non-null    float64
dtypes: float64(11), int64(5), object(9)
memory usage: 40.2+ KB

Agar lebih mudah melihat set data saat Anda mulai mengkodekan, hapus kolom yang tidak akan Anda gunakan.

In [7]:
df_car.columns

Index(['symboling', 'normalized-losses', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price'], dtype='object')

In [8]:
df_car = df_car[[ 'aspiration', 'num-of-doors',  'drive-wheels',  'num-of-cylinders']].copy()

Anda sekarang memiliki empat kolom. Kolom ini semua berisi nilai-nilai teks.

In [9]:
df_car.head()

  aspiration num-of-doors drive-wheels num-of-cylinders
0        std          two          rwd             four
1        std          two          rwd             four
2        std          two          rwd              six
3        std         four          fwd             four
4        std         four          4wd             five

Kebanyakan algoritme machine learning memerlukan input berupa nilai-nilai numerik. 

- Fitur **num-of-cylinders** dan **num-of-doors** memiliki nilai ordinal. Anda dapat mengubah nilai-nilai fitur ini menjadi rekan numeriknya.
- Namun, **aspiration** dan **drive-wheels** tidak memiliki nilai ordinal. Fitur-fitur ini harus dikonversi secara berbeda.

Anda akan melihat isi fitur ordinal terlebih dahulu.

# Langkah 2: Mengkodekan fitur ordinal

Pada langkah ini, Anda akan menggunakan fungsi mapper untuk mengubah fitur ordinal menjadi nilai numerik terurut.

Mulailah dengan mendapatkan jenis kolom baru dari DataFrame:

In [10]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   aspiration        205 non-null    object
 1   num-of-doors      203 non-null    object
 2   drive-wheels      205 non-null    object
 3   num-of-cylinders  205 non-null    object
dtypes: object(4)
memory usage: 6.5+ KB

Pertama, tentukan nilai apa yang terdapat dalam kolom ordinal. 

Dimulai dengan fitur **num-of-doors**, Anda dapat menggunakan `value_counts` untuk menemukan nilai-nilai.

In [11]:
df_car['num-of-doors'].value_counts()

num-of-doors
four    114
two      89
Name: count, dtype: int64

Fitur ini hanya memiliki dua nilai: *empat* dan *dua*. Anda dapat membuat mapper sederhana yang berisi kamus:

In [12]:
door_mapper = {"two": 2,
              "four": 4}

Anda kemudian dapat menggunakan metode `replace` dari pandas untuk menghasilkan kolom numerik baru berdasarkan kolom **num-of-doors**.

In [16]:
df_car['doors'] = df_car["num-of-doors"].replace(door_mapper)

/tmp/ipykernel_35440/1675203305.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_car['doors'] = df_car["num-of-doors"].replace(door_mapper)

Ketika Anda menampilkan DataFrame, Anda akan melihat kolom baru di sebelah kanan. Ini berisi representasi numerik dari jumlah pintu.

In [17]:
df_car.head()

  aspiration num-of-doors drive-wheels num-of-cylinders  doors
0        std          two          rwd             four    2.0
1        std          two          rwd             four    2.0
2        std          two          rwd              six    2.0
3        std         four          fwd             four    4.0
4        std         four          4wd             five    4.0

Ulangi proses dengan kolom **num-of-cylinders**.

Pertama, dapatkan nilainya.

In [18]:
df_car['num-of-cylinders'].value_counts()

num-of-cylinders
four      159
six        24
five       11
eight       5
two         4
twelve      1
three       1
Name: count, dtype: int64

Selanjutnya, buat mapper.

In [19]:
cylinder_mapper = {"two":2,
                  "three":3,
                  "four":4,
                  "five":5,
                  "six":6,
                  "eight":8,
                  "twelve":12}

Menerapkan mapper dengan menggunakan metode `replace`.

In [21]:
df_car['cylinders'] = df_car['num-of-cylinders'].replace(cylinder_mapper)

/tmp/ipykernel_35440/725182840.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_car['cylinders'] = df_car['num-of-cylinders'].replace(cylinder_mapper).infer_objects(copy=False)

In [22]:
df_car.head()

  aspiration num-of-doors drive-wheels num-of-cylinders  doors  cylinders
0        std          two          rwd             four    2.0          4
1        std          two          rwd             four    2.0          4
2        std          two          rwd              six    2.0          6
3        std         four          fwd             four    4.0          4
4        std         four          4wd             five    4.0          5

Untuk informasi lebih lanjut tentang metode `replace`, lihat [pandas.DataFrame.replace](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html) dalam dokumentasi pandas.

# Langkah 3: Mengkodekan data kategoris non-ordinal

Pada langkah ini, Anda akan mengkodekan data non-ordinal dengan menggunakan metode `get_dummies` dari pandas.

Dua fitur yang tersisa tidak ordinal. 

Menurut deskripsi atribut, nilai berikut mungkin dilakukan:

- aspiration: std, turbo. 
- roda penggerak: 4wd, fwd, rwd. 

Anda mungkin berpikir bahwa strategi yang tepat adalah mengkonversi nilai-nilai ini menjadi nilai numerik. Misalnya, pertimbangkan fitur **drive-wheels**. Anda bisa menggunakan *4wd = 1*, *fwd = 2*, dan *rwd = 3*. Namun, *fwd* tidak kurang dari *rwd*. Nilai-nilai ini tidak memiliki urutan, tetapi Anda baru saja memasukannya dengan menetapkan nilai numerik ini.

Strategi yang benar adalah mengubah nilai-nilai ini menjadi *fitur biner* untuk setiap nilai dalam fitur asli. Proses ini sering disebut *pengkode one-hot* dalam machine learning, atau *dummying* dalam statistik.

pandas menyediakan metode `get_dummies`, yang mengubah data menjadi fitur biner. Untuk informasi lebih lanjut, lihat [pandas.get_dummies](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html) dalam dokumentasi pandas.

Menurut deskripsi atribut, **drive-wheels** memiliki tiga nilai yang mungkin.

In [23]:
df_car['drive-wheels'].value_counts()

drive-wheels
fwd    120
rwd     76
4wd      9
Name: count, dtype: int64

Gunakan metode `get_dummies` untuk menambahkan fitur biner baru ke DataFrame.

In [24]:
df_car = pd.get_dummies(df_car,columns=['drive-wheels'])

In [25]:
df_car.head()

  aspiration num-of-doors num-of-cylinders  doors  cylinders  drive-wheels_4wd  drive-wheels_fwd  drive-wheels_rwd
0        std          two             four    2.0          4             False             False              True
1        std          two             four    2.0          4             False             False              True
2        std          two              six    2.0          6             False             False              True
3        std         four             four    4.0          4             False              True             False
4        std         four             five    4.0          5              True             False             False

Ketika Anda memeriksa set data, Anda akan melihat tiga kolom baru di sebelah kanan: 

- **drive-wheels_4wd**
- **drive-wheels_fwd**
- **drive-wheels_rwd**

Pengkodeannya bersifat langsung Jika nilai di kolom **drive-wheels** adalah *4wd*, maka *1* adalah nilai di kolom **drive-wheels_4wd**. *0* adalah nilai untuk kolom lain yang dihasilkan. Jika nilai dalam kolom **drive-wheels** adalah *fwd*, maka *1* adalah nilai di kolom **drive-wheels_fwd**, dan seterusnya.

Fitur biner ini memungkinkan Anda untuk mengekspresikan informasi dengan cara numerik, tanpa menyiratkan urutan apa pun.

Periksa kolom terakhir yang akan Anda kodekan.

Data dalam kolom **aspiration** hanya memiliki dua nilai: *std* dan *turbo*. Anda bisa mengkodekan kolom ini menjadi dua fitur biner. Namun, Anda juga dapat mengabaikan nilai *std* dan merekam apakah itu *turbo* atau bukan. Untuk melakukannya, Anda masih akan menggunakan metode `get_dummies` ini, tetapi tentukan `drop_first` sebagai *Betul*.

In [26]:
df_car['aspiration'].value_counts()

aspiration
std      168
turbo     37
Name: count, dtype: int64

In [27]:
df_car = pd.get_dummies(df_car,columns=['aspiration'], drop_first=True)

In [28]:
df_car.head()

  num-of-doors num-of-cylinders  doors  cylinders  drive-wheels_4wd  drive-wheels_fwd  drive-wheels_rwd  aspiration_turbo
0          two             four    2.0          4             False             False              True             False
1          two             four    2.0          4             False             False              True             False
2          two              six    2.0          6             False             False              True             False
3         four             four    4.0          4             False              True             False             False
4         four             five    4.0          5              True             False             False             False

**Tugas Tantangan:** Kembali ke awal lab ini, dan tambahkan kolom lain ke set data. Bagaimana Anda akan mengkodekan nilai-nilai dari setiap kolom? Memperbarui kode untuk menyertakan beberapa fitur lainnya.

# Selamat!

Anda telah menyelesaikan lab ini, dan sekarang Anda dapat mengakhirinya dengan mengikuti petunjuk panduan lab tersebut.